Gather all errors before bailing.
This is similar to what we now do in `pre-push`.

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -5,12 +5,13 @@
 # Executes tests against the code about to be submitted.  It makes a copy of
 # the worktree using "git worktree", then patches in the *staged* changes
 # (either those manually staged via "git add" or those generated by a
-# standalone "git commit").  Then it runs the test.  If it passes, it cleans
-# up.  This will cause git to leak worktrees, but that should not really be a
-# problem.  Eventually the tempdir will be cleaned, and eventually git will
-# detect the directories and clean up those things as well.
+# standalone "git commit").  Then it runs the tests.
 
-# If you want to manually clean up, something like the following works well:
+# If this crashes, it will cause git to leak worktrees, but that should not
+# really be a problem.  Eventually the tempdir will be cleaned, and eventually
+# git will detect the directories and clean up the worktree entries as well.
+
+# If you need to manually clean up, something like the following works well:
 
 # git worktree prune -n  # To see what would be pruned
 # git worktree prune -v  # To see what was pruned
@@ -22,7 +23,6 @@
 #     git worktree remove -f $wt
 #   done
 
-# Yes, the following causes worktrees to leak
 set -u
 
 export PAGER=cat
@@ -42,11 +42,22 @@ pushd "${dir}" > /dev/null || exit
 git apply --allow-empty "${patchfile}"
 git diff --stat
 
-# This is the test we want to run.
-eslint . || exit
-hooks/style_linter.py || exit
+messages=()
+# These are the tests we want to run.
+eslint . || messages+=('eslint failed')
+hooks/style_linter.py || messages+=('style linter failed')
 
 # Clean up.
 popd > /dev/null || exit
 git worktree remove --force "${dir}"
 rm "${patchfile}"
+
+cnt=${#messages[*]}
+
+if ((cnt)); then
+  echo "Issues found (${cnt}):"
+  for msg in "${messages[@]}"; do
+    echo "${msg}"
+  done
+  exit 1
+fi
